server:
  port: 8090

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      import: optional:configserver:http://localhost:8090
      server:
        native:
          search-locations: classpath:/config/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
